CREATE DATABASE `htnews` /*!40100 COLLATE 'utf8_general_ci' */;


CREATE USER 'htuser'@'localhost' IDENTIFIED BY 'htuser';
GRANT USAGE ON *.* TO 'htuser'@'localhost';
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `htnews`.* TO 'htuser'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'htuser'@'localhost';


